### ISSUE TITLE
Frame Size Issue

### ISSUE THREAD

**Issue by vidhithakkar12** [anand498/Face-Liveness-Detection#1]
Hi Anand,

I was exploring your code and while executing it I got the frame as attached below where the blue box seems to be incomplete. Could you please help me with the hardware requirements of the camera used by you ?

My current frame size is 640 x 480.

Looking forward to hear from you soon.

Thanks and Regards,
Vidhi

![Liveness](https://user-images.githubusercontent.com/42344939/65688823-6029bc00-e089-11e9-8780-69e0246de4ca.png)

**Comment by anand498** [comment]
Hi,
    So the idea behind adding the blue window frame was to take the picture information within that window. In your case I think you need to change some parameters with respect to the size of the window of the camera frame. It has got nothing to do with the camera specifications.

*cv2.rectangle(frame, (400, 100), (900, 550), (255,0,0), 2)*
(400,100) is the top left corner of the frame.
(900,550) is the bottom right corner of the frame.
so this was the cropped frame input in my case. you would have to change(probably decrease them) the first two tuples according to your convenience.
Thanks.

**Comment by vidhithakkar12** [comment]
Thank you Anand, I trained the model by generating data from data creation scripts and changed the frame size, however when I run facepredictor.py it doesn't predicted whether the face is real or fake. 

Here is an image with the original frame size (the one that you have used).

![Picture2](https://user-images.githubusercontent.com/42344939/66113306-26f1ce80-e5ea-11e9-9d10-13056725ae87.png)


Here is an image with changed frame size.

![Picture1](https://user-images.githubusercontent.com/42344939/66113332-31ac6380-e5ea-11e9-8338-0b6ec45df311.png)

**Comment by anand498** [comment]
The way in which the facepredictor file works is when the face is detected within the area of the blue window frame. The size of the face detected should be more than 1/2 of the size of the frame. Only then will the face predictor work and real time results('real' or 'fake' )will be displayed in the window. As far as the frame size is concerned, the size of my camera image are the values uploaded in the facepredictor python file.
Thanks.

**Comment by vidhithakkar12** [comment]
Thank you so much Anand for all your help. The code is working perfectly fine now.
