### ISSUE TITLE
Model size after training

### ISSUE THREAD

**Issue by benachraf** [anand498/Face-Liveness-Detection#7]
Hello,
I noticed you model size is about 101MB, but when i trained the model with my own dataset, my final model is of size 393MB.
How did you save the model after training so we can have an optimized size of the model?
Thank you

**Comment by anand498** [comment]
Hey,
     The size of the models highly depend on multiple factors
1. dataset size and dimensions of images for training
2. model parameters, training parameters etc. 
For saving the model I used Keras model function
`model.save({filepath})`
